stages:
  - build

default:
  tags:
    - zloserver

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/

lint:
  stage: build
  image: node:14.21.2-alpine
  script:
    - npm install
    - npm run lint
  only:
    - tags

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/risegta/tools/qa-panel/qa-panel:latest -t $CI_REGISTRY/risegta/tools/qa-panel/qa-panel:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY/risegta/tools/qa-panel/qa-panel:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/risegta/tools/qa-panel/qa-panel:latest
  only:
    - tags